#!/usr/bin/python3
# welcome user
print("Welcome to Grade Calculator")
print()
# get name of exam
subject = input("What Subject: ")
print()

#possible maximum score
totalScore = int(input("maximum score: "))

# user score
userScore = int(input("what was your score: "))
print()

#your score divided by total score
score = float(userScore / totalScore)

# round score to 2.f
finalScore = round(score, 2)

percent = round(float(userScore / totalScore)*100, 2)

print("you scored", percent, "%")

if finalScore >= .90:
  print("A+")
elif finalScore >= .80 and finalScore <= .89:
  print("A-")
elif finalScore >= .70 and finalScore <= .79:
  print("B")
elif finalScore >= .60 and finalScore <= .69:
  print("C")
elif finalScore >= .50 and finalScore <= .59:
  print("D")
elif finalScore <= .49:
  print("F")
else:
  print("try again")
